# Generated by Django 3.2.4 on 2021-06-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210605_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antiqueitems',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='autobidsettings',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='bid_owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='autobidsettings',
            name='my_money',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AutoBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('is_automatic', models.BooleanField(default=False)),
                ('antique_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.antiqueitems')),
            ],
        ),
    ]
